# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/infra/values"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "04:00"
    commit-message:
      prefix: "infra"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: "docker"
    directory: "/k8s/values"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "04:00"
    commit-message:
      prefix: "k8s"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "terraform"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
