# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/infra/values"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "infra"
  - package-ecosystem: "docker"
    directory: "/k8s/values"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "k8s"
