clusterIssuer:
  acme:
    email: webmaster@fabinfra.net
    http01:
      ingress:
        podTemplate:
          spec:
            nodeSelector:
              server-role-web: 'true'
  ca:
    root:
      name: fcprod-root-ca
      # crt: toComplete
      # key: toComplete
    intermediate:
      - name: fabinfra-staging-ca1
        cn: FabInfra Staging CA1
      - name: fabinfra-prod-ca1
        cn: FabInfra Production CA1
