# Default values for cert-manager-config.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

clusterIssuer:
  acme:
    email: ""
    http01:
      ingress:
        podTemplate: {}
        ingressTemplate: {}
  ca:
    root:
      name: fcprod-root-ca
      # crt: toComplete
      # key: toComplete
    intermediate:
      - name: fabinfra-staging-ca1
        cn: FabInfra Staging CA1
      - name: fabinfra-prod-ca1
        cn: FabInfra Production CA1
