# Default values for apm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: docker.elastic.co/apm/apm-server
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

ingress:
  enabled: false
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
  hosts:
    - host: example.org
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: example-tls
  #    hosts:
  #      - example.org

nodeSelector:
  server-role-infra: "true"

tolerations: []

affinity: {}

elasticsearchRef:
  name: elasticsearch

kibanaRef:
  name: kibana

config: {}
