apiVersion: v1
kind: Service
metadata:
  name: {{ include "mailserver.fullname" . }}
  labels:
    {{- include "mailserver.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- if .Values.service.port.smtp }}
    - port: {{ .Values.service.port.smtp }}
      targetPort: smtp
      protocol: TCP
      name: smtp
    {{- end }}
    {{- if .Values.service.port.submission }}
    - port: {{ .Values.service.port.submission }}
      targetPort: submission
      protocol: TCP
      name: submission
    {{- end }}
  selector:
    {{- include "mailserver.selectorLabels" . | nindent 4 }}
