fullnameOverride: backups

image:
  repository: ghcr.io/fab-infra/backuptools
  tag: opensuse16-20260728-1847-563bf6e

podSecurityContext:
  runAsUser: 1000
  runAsGroup: 1000

nodeSelector:
  server-role-infra: "true"

backends:
  gcs:
    bucket: fabinfra-net-backups
  s3:
    provider: OVH
    region: rbx
    bucket: fabinfra-net-backups

backups:
  sync:
    backends: s3,gcs
    args: |
      s3:fabinfra-net-backups gcs:fabinfra-net-backups --checksum

schedules:
  sync: "30 3 * * *"
