fullnameOverride: certificates

certificates:
  # VPN servers
  - name: ks14
    cn: ks14.srv.fabinfra.net
    dnsNames:
      - ks14.srv.fabinfra.net
    usages:
      - digital signature
      - key encipherment
      - server auth
    issuerRef:
      name: fabinfra-prod-ca1
      kind: ClusterIssuer
  - name: vpn-server
    cn: vpn-server
    dnsNames:
      - vpn.fabinfra.net
    usages:
      - digital signature
      - key encipherment
      - server auth
    issuerRef:
      name: fabinfra-prod-ca1
      kind: ClusterIssuer
  # VPN clients (servers)
  - name: od01
    cn: od01.srv.fabinfra.net
    dnsNames:
      - od01.srv.fabinfra.net
    usages:
      - digital signature
      - key encipherment
      - client auth
    issuerRef:
      name: fabinfra-prod-ca1
      kind: ClusterIssuer
  - name: rb04
    cn: rb04.srv.fabinfra.net
    dnsNames:
      - rb04.srv.fabinfra.net
    usages:
      - digital signature
      - key encipherment
      - client auth
    issuerRef:
      name: fabinfra-prod-ca1
      kind: ClusterIssuer
  # VPN clients (devices)
  - name: fab-precision3580
    dnsNames:
      - fab-precision3580.home.crespel.me
    usages:
      - digital signature
      - key encipherment
      - client auth
    issuerRef:
      name: fabinfra-prod-ca1
      kind: ClusterIssuer
  - name: fab-precision7530
    dnsNames:
      - fab-precision7530.home.crespel.me
    usages:
      - digital signature
      - key encipherment
      - client auth
    issuerRef:
      name: fabinfra-prod-ca1
      kind: ClusterIssuer
  - name: fab-iphone
    dnsNames:
      - fab-iphone.home.crespel.me
    usages:
      - digital signature
      - key encipherment
      - client auth
    issuerRef:
      name: fabinfra-prod-ca1
      kind: ClusterIssuer
  - name: fab-gts2
    dnsNames:
      - fab-gts2.home.crespel.me
    usages:
      - digital signature
      - key encipherment
      - client auth
    issuerRef:
      name: fabinfra-prod-ca1
      kind: ClusterIssuer
  - name: fab-gta9
    dnsNames:
      - fab-gta9.home.crespel.me
    usages:
      - digital signature
      - key encipherment
      - client auth
    issuerRef:
      name: fabinfra-prod-ca1
      kind: ClusterIssuer
  - name: jean-laptop
    dnsNames:
      - jean-laptop.home.crespel.me
    usages:
      - digital signature
      - key encipherment
      - client auth
    issuerRef:
      name: fabinfra-prod-ca1
      kind: ClusterIssuer
