fullnameOverride: jobs

nodeSelector:
  server-role-infra: "true"

schedules:
  certbot-renew: "30 1 * * *"

volumes:
  letsencrypt:
    config:
      hostPath:
        path: /etc/letsencrypt
        type: DirectoryOrCreate
    logs:
      hostPath:
        path: /var/log/letsencrypt
        type: DirectoryOrCreate
    work:
      hostPath:
        path: /var/lib/letsencrypt
        type: DirectoryOrCreate
