fullnameOverride: kibana

podSecurityContext:
  runAsUser: 1000
  runAsGroup: 1000

nodeSelector:
  server-role-infra: 'true'

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
  hosts:
    - host: "kibana.fabinfra.net"
      paths:
        - path: "/"
          pathType: ImplementationSpecific
  tls:
    - secretName: kibana-tls
      hosts:
        - "kibana.fabinfra.net"

config:
  server.publicBaseUrl: "https://kibana.fabinfra.net"
