fullnameOverride: logstash

podSecurityContext:
  runAsUser: 1000
  runAsGroup: 1000

env:
  ELASTICSEARCH_CACERT: /usr/share/logstash/config/elasticsearch-certs/ca.crt
  ELASTICSEARCH_HOSTS: https://infra-es-http:9200
  ELASTICSEARCH_USERNAME: elastic
  LS_JAVA_OPTS: -Xms512m -Xmx512m
  XPACK_MONITORING_ENABLED: "false"

config:
  activemq.conf: |
    output {
      # JKA Server Log
      if "jka-games" in [tags] {
        stomp {
          host => "activemq.domain-jediholo-net.svc"
          port => 61613
          destination => "/topic/jka.%{modname}.%{servername}.games.log"
          headers => [ "amq-msg-type", "text", "type", "%{type}" ]
        }
      }
    }

volumes:
  - name: data
    hostPath:
      path: /home/apps/logstash/data
      type: DirectoryOrCreate
  - name: config
    secret:
      secretName: logstash-config
  - name: elasticsearch-certs
    secret:
      secretName: infra-es-http-certs-public
  - name: domains
    hostPath:
      path: /home/domains
      type: DirectoryOrCreate
  - name: jka
    hostPath:
      path: /home/jka
      type: DirectoryOrCreate
volumeMounts:
  - mountPath: /usr/share/logstash/data
    name: data
  - mountPath: /usr/share/logstash/pipeline/activemq.conf
    name: config
    subPath: activemq.conf
    readOnly: true
  - mountPath: /usr/share/logstash/config/elasticsearch-certs
    name: elasticsearch-certs
    readOnly: true
  - mountPath: /home/domains
    name: domains
    readOnly: true
  - mountPath: /home/jka
    name: jka
    readOnly: true
