{{- if .Values.clusterIssuer.ca.root }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.clusterIssuer.ca.root.name }}-tls
  labels:
    {{- include "certmanagerConfig.labels" . | nindent 4 }}
type: Opaque
stringData:
  tls.crt: {{ .Values.clusterIssuer.ca.root.crt | quote }}
  tls.key: {{ .Values.clusterIssuer.ca.root.key | quote }}
{{- end }}
