{{- if .Values.secrets.ftp.username }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backups.fullname" . }}-ftp-user
  labels:
    {{- include "backups.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.secrets.ftp.username }}
  password: {{ .Values.secrets.ftp.password }}
{{- end }}
---
{{- if .Values.secrets.gcs.sa }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backups.fullname" . }}-sa
  labels:
    {{- include "backups.labels" . | nindent 4 }}
type: Opaque
stringData:
  backup-sa.json: {{ .Values.secrets.gcs.sa | b64dec | quote }}
{{- end }}
---
{{- if .Values.secrets.s3.accessKeyId }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backups.fullname" . }}-s3-creds
  labels:
    {{- include "backups.labels" . | nindent 4 }}
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: {{ .Values.secrets.s3.accessKeyId }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.secrets.s3.secretAccessKey }}
{{- end }}
---
{{- if .Values.secrets.swift.openrc }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backups.fullname" . }}-openrc
  labels:
    {{- include "backups.labels" . | nindent 4 }}
type: Opaque
stringData:
  backup-openrc.sh: {{ .Values.secrets.swift.openrc | quote }}
{{- end }}
